name: workflow

on:
    push:
        branches:
            - main
        paths-ignore:
            - 'README.md'

jobs:
    integration:
      name: Continuous Integration
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint code
        uses: echo "Linting repository"

      - name: Run unit tests Code
        uses: echo "Running unit tests"


    build-and-push-ecr-image:
      name:  Continuous Delivery
      needs: integration
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Utilities Code
        runs:  |
          sudo apt-get update
          sudo apt-get install -y jq unzip

      - name: Configure AWS credentials Code
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-REGION: ${{ secrets.AWS_ACCESS_KEY_ID }}
          
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

        


      



